

/**
 * Brands.jsx
 * 
 * This is the page for managing brands.
 * It displays a list of brands and provides a form to add new brands.
 * Some styling was generated by AI with expirmenation (Inline Vscode IDE Microsoft Copilot) on what looked the best visually (This file is still a work in progress)
 * AI genereated me snippets of code for breadcrumbs and I adapted it my own code. (Vscode AI Copilot)
 * Expiremantion on this file is still in progress
 * Look back at W3 Schools on more ways to style this file
 * 
 */
import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import getBrands from '../api/getBrands'

export default function Brands() {
    const [name, setName] = useState('')
    const [domain, setDomain] = useState('')
    const [instagramUrl, setInstagramUrl] = useState('')
    const [tiktokUrl, setTiktokUrl] = useState('')

    const [loading, setLoading] = useState(false)
    const [msg, setMsg] = useState('')
    const [brands, setBrands] = useState([])

    // Search
    const [searchQuery, setSearchQuery] = useState('')

    const [isFormVisible, setIsFormVisible] = useState(false)

    // Load brands on mount of app
    useEffect(() => {
        getBrands().then((data) => setBrands(data))
    }, [])

    // Add Brand Submit btn
    async function onSubmit(e) {
        e.preventDefault()
        if (!name.trim() || !domain.trim()) return
        setLoading(true)
        setMsg('')

        // Remove protocol if present to avoid duplication
        // e.g. https://google.com -> google.com
        let cleanDomain = domain.trim().replace(/^https?:\/\//, '').replace(/\/$/, '')

        try {
            const res = await fetch('/api/brands', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    name: name.trim(),
                    domain: cleanDomain,
                    instagramUrl: instagramUrl.trim() || null,
                    tiktokUrl: tiktokUrl.trim() || null
                }),
            })

            const data = await res.json().catch(() => ({}))
            setLoading(false)

            if (!res.ok) {
                setMsg(data.message || 'Create failed')
                return
            }

            // append my new brand
            if (data && data.brand) {
                setBrands(prev => [data.brand, ...prev])
                setMsg('Brand added successfully!')
                setIsFormVisible(false)
            }

            setName('')
            setDomain('')
            setInstagramUrl('')
            setTiktokUrl('')

        } catch (err) {
            console.error(err)
            setLoading(false)
            setMsg('Error submitting form')
        }
    }

    return (
        <div style={{ minHeight: '100vh', width: '100%', backgroundColor: '#B3B3B3', paddingBottom: '100px', padding: '24px', boxSizing: 'border-box' }}>

            {/* Breadcrumbs */}
            <nav style={{ marginBottom: '16px', fontSize: '14px', color: '#666', padding: '0 8%' }}>
                <Link to="/" style={{ color: '#888', textDecoration: 'none' }}>Home</Link>
                <span style={{ margin: '0 8px' }}>&gt;</span>
                <span style={{ color: '#333', fontWeight: 500 }}>Brands</span>
            </nav>

            {/* --- HEADER --- */}
            <header style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '24px',
                padding: '0 8%'
            }}>
                <h1 style={{ margin: 0, fontSize: '2rem' }}>Brands</h1>

                {/* Toggle Form Button */}
                <button
                    onClick={() => setIsFormVisible(!isFormVisible)}
                    style={{
                        backgroundColor: '#bdfdbdff',
                        color: 'black',
                        border: 'none',
                        padding: '10px 20px',
                        fontSize: '14px',
                        fontStyle: 'italic',
                        cursor: 'pointer'
                    }}
                >
                    {isFormVisible ? 'Close Form' : 'Add Brand'}
                </button>
            </header>

            {/* --- FILTERS SECTION --- */}
            <div style={{
                backgroundColor: '#D9D9D9',
                padding: '32px',
                borderRadius: '12px',
                boxShadow: '0 4px 12px rgba(241, 82, 19, 0.25)',
                display: 'flex',
                flexWrap: 'wrap',
                gap: '24px',
                justifyContent: 'center',
                alignItems: 'center',
                margin: '0 8% 40px 8%'
            }}>
                {/* Search */}
                <div style={{ flex: '0 1 300px' }}>
                    <label style={{ display: 'block', marginBottom: '8px', fontWeight: 600, fontSize: '14px', color: '#333' }}>Search</label>
                    <input
                        type="text"
                        placeholder="Search for a brand..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid #ddd' }}
                    />
                </div>
            </div>

            {/* --- ADD BRAND FORM --- */}
            {isFormVisible && (
                <section style={{
                    marginBottom: '100px',
                    padding: '60px 40px',
                    backgroundColor: '#D9D9D9',
                    borderRadius: '12px',
                    boxShadow: '0 4px 12px rgba(241, 82, 19, 0.25)',
                    textAlign: 'center', // Center header and text
                    margin: '0 8% 100px 8%' // Match padding of layout, push grid way down
                }}>


                    <h3 style={{ marginTop: 0 }}>Add New Competitor</h3>
                    <form onSubmit={onSubmit} style={{
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '12px',
                        maxWidth: '400px',
                        margin: '0 auto', // Center the form itself
                        justifyContent: 'center',
                    }}>



                        <div style={{ textAlign: 'left' }}>
                            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>Brand Name</label>
                            <input
                                style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid #ddd' }}
                                placeholder="e.g. Brand Name"
                                value={name}
                                onChange={e => setName(e.target.value)}
                            />
                        </div>

                        <div style={{ textAlign: 'left' }}>
                            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>Domain</label>
                            <input
                                style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid #ddd' }}
                                placeholder="e.g. brand.com"
                                value={domain}
                                onChange={e => setDomain(e.target.value)}
                            />
                            <span style={{ fontSize: '11px', color: '#000000ff' }}>Enter just domain or full URL (https will be cleaned)</span>
                        </div>



                        <div style={{ textAlign: 'left' }}>
                            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>Instagram URL</label>
                            <input
                                style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid #ddd' }}
                                placeholder="https://instagram.com/brand_name"
                                value={instagramUrl}
                                onChange={e => setInstagramUrl(e.target.value)}
                            />
                        </div>

                        <div style={{ textAlign: 'left' }}>
                            <label style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>TikTok URL</label>
                            <input
                                style={{ width: '100%', padding: '10px', borderRadius: '6px', border: '1px solid #ddd' }}
                                placeholder="https://tiktok.com/@brand_name"
                                value={tiktokUrl}
                                onChange={e => setTiktokUrl(e.target.value)}
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loading}
                            style={{
                                marginTop: '8px',
                                padding: '12px',
                                backgroundColor: 'rgba(241, 82, 19, 0.93)',
                                color: 'white',
                                border: 'none',
                                borderRadius: '6px',
                                fontWeight: 600,
                                cursor: 'pointer'
                            }}
                        >
                            {loading ? 'Saving...' : 'Save Brand'}
                        </button>
                    </form>
                    {msg && <p style={{ marginTop: '10px', color: msg.includes('failed') ? 'red' : 'green' }}>{msg}</p>}
                </section>
            )}






            {/* --- BRANDS GRID --- */}
            <section style={{ padding: '0 8%' }}>
                <div style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(5, 1fr)', // 5 columns wide for now
                    gap: '20px'
                }}>
                    {brands
                        .filter(brand => brand.name.toLowerCase().includes(searchQuery.toLowerCase()))
                        .map(brand => (
                        <div key={brand._id || brand.id} style={{
                            backgroundColor: '#D9D9D9',
                            borderRadius: '12px',
                            padding: '24px',
                            boxShadow: '0 4px 12px rgba(241, 82, 19, 0.25)',
                            display: 'flex',
                            flexDirection: 'column',
                            justifyContent: 'space-between',
                            minHeight: '150px'
                        }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
                                <img 
                                    src={`https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://${brand.domain}&size=128`} 
                                    onError={(e) => { 
                                        e.target.src = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'; 
                                        e.target.onerror = null; 
                                    }}
                                    style={{ width: '50px', height: '50px', padding: '6px', borderRadius: '50%', objectFit: 'contain', backgroundColor: '#fff', boxShadow: '0 2px 4px rgba(0,0,0,0.1)', boxSizing: 'border-box' }} 
                                    alt={brand.name} 
                                />
                                <div style={{ transition: 'margin 0.2s ease' }}>
                                    <h3 style={{ margin: '0 0 4px 0', fontSize: '1.1rem' }}>
                                        <Link to={`/brands/${brand._id || brand.id}`} style={{ textDecoration: 'none', color: '#000' }}>
                                            {brand.name}
                                        </Link>
                                    </h3>
                                    <p style={{ margin: '0 0 12px 0', fontSize: '13px', color: '#666', wordBreak: 'break-all' }}>
                                        <a href={`https://${brand.domain}`} target="_blank" rel="noopener noreferrer" style={{ color: '#888', textDecoration: 'none' }}>
                                            {brand.domain}
                                        </a>
                                    </p>
                                </div>
                            </div>

                            <div style={{ fontSize: '12px', color: '#555', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                    <span>Collections:</span>
                                    <strong>{brand.collection_count || 0}</strong>
                                </div>

                                {brand.tags && brand.tags.length > 0 && (
                                    <div style={{ marginTop: '4px' }}>
                                        {brand.tags.slice(0, 3).map(t => (
                                            <span key={t} style={{
                                                background: '#f0f0f0',
                                                padding: '2px 6px',
                                                borderRadius: '4px',
                                                marginRight: '4px',
                                                fontSize: '10px'
                                            }}>
                                                #{t}
                                            </span>
                                        ))}
                                    </div>
                                )}

                                {brand.instagramUrl && (
                                    <div style={{ marginTop: '8px', paddingTop: '8px', borderTop: '1px solid #f0f0f0' }}>
                                        <a href={brand.instagramUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#007bff', wordBreak: 'break-all', fontSize: '11px' }}>
                                            {brand.instagramUrl}
                                        </a>
                                    </div>
                                )}

                                {brand.tiktokUrl && (
                                    <div style={{ marginTop: '8px', paddingTop: '8px', borderTop: '1px solid #f0f0f0' }}>
                                        <a href={brand.tiktokUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#007bff', wordBreak: 'break-all', fontSize: '11px' }}>
                                            {brand.tiktokUrl}
                                        </a>
                                    </div>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
                {brands.length === 0 && <p style={{ color: '#888', textAlign: 'center', marginTop: '40px' }}>No brands found. Click "Add Brand" to start.</p>}
            </section>
        </div>
    )
}
