/**
 * BrandDetails.jsx
 * 
 * This is the page for managing brand details.
 * It displays a list of brand details 
 * Some styling was generated by AI with expirmenation (Inline Vscode IDE Microsoft Copilot) on what looked the best visually (This file is still a work in progress)
 * Expiremantion on this file is still in progress
 * AI helped with debugging the brand fetching in the back end a lot (Inline Vscode IDE Microsoft Copilot) when I was stuck on why my brands werent showing up + displaying the collections. I was having issues with the collections not showing up. 
 * Specific debgubg and working code snippets (lines 21-32, 99-108, 118 -133)
 * 
 */
import React, { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, PieChart, Pie, Cell } from 'recharts';
import { useExchangeRate } from '../hooks/useExchangeRate';
import BrandSocials from '../components/BrandSocials';


export default function BrandDetails() {
    const { brandId } = useParams();
    const navigate = useNavigate();
    const [brand, setBrand] = useState(null);
    const [loading, setLoading] = useState(true);
    const [analytics, setAnalytics] = useState(null);
    const [analyticsHoodies, setAnalyticsHoodies] = useState(null);
    const [analyticsAllProducts, setAnalyticsAllProducts] = useState(null);


    const [distribution, setDistribution] = useState([]);

    const [isEditing, setIsEditing] = useState(false);
    const [editData, setEditData] = useState({ instagramUrl: '', tiktokUrl: '', tags: '', baseCurrency: '' });

    const { rates, convertToUSD } = useExchangeRate();

    useEffect(() => {
        const fetchBrand = async () => {
            try {
                const res = await fetch(`/api/brands/details/${brandId}`);
                if (res.ok) {
                    const data = await res.json();
                    setBrand(data);
                }
            } catch (error) {
                console.error("Failed to fetch brand", error);
            } finally {
                setLoading(false);
            }
            if (brandId) {
                fetch(`/api/analytics/brand/${brandId}?product_type=T-Shirt`)
                    .then(res => res.json())
                    .then(data => setAnalytics(data))
                    .catch(err => console.error(err));
            }
            if (brandId) {
                fetch(`/api/analytics/brand/${brandId}?product_type=Hoodie`)
                    .then(res => res.json())
                    .then(data => setAnalyticsHoodies(data))
                    .catch(err => console.error(err));
            }
            if (brandId) {
                fetch(`/api/analytics/brand/${brandId}`)
                    .then(res => res.json())
                    .then(data => setAnalyticsAllProducts(data))
                    .catch(err => console.error(err));

                fetch(`/api/analytics/brand/${brandId}/distribution`)
                    .then(res => res.json())
                    .then(data => setDistribution(data))
                    .catch(err => console.error(err));
            }
        };
        fetchBrand();
    }, [brandId]);

    const COLORS = ['#8ca7beff', '#466963ff', '#584823ff', '#b38670ff', '#22222eff']; {/**Some Colors I like */ }

    if (loading) return <div style={{ padding: 24 }}>Loading...</div>;

    // Debugging View if not found
    if (!brand) {
        return (
            <div style={{ padding: 24 }}>
                <h2>Brand not found</h2>
                <p>Could not find brand with ID: <strong>{brandId}</strong></p>
                <p>Please return to the <Link to="/brands">Brands List</Link>.</p>
            </div>
        );
    }

    return (
        <div style={{ padding: '24px', paddingBottom: '100px' }}>
            {/* Breadcrumbs */}
            <nav style={{ marginBottom: '24px', fontSize: '14px', color: '#666' }}>
                <Link to="/" style={{ color: '#888', textDecoration: 'none' }}>Home</Link>
                <span style={{ margin: '0 8px' }}>&gt;</span>
                <Link to="/brands" style={{ color: '#888', textDecoration: 'none' }}>Brands</Link>
                <span style={{ margin: '0 8px' }}>&gt;</span>
                <span style={{ color: '#333', fontWeight: 500 }}>{brand.name}</span>
            </nav>

            {/* Header */}
            <header style={{ marginBottom: '32px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                    <h1 style={{ margin: '0 0 8px 0', fontSize: '2.5rem' }}>{brand.name}</h1>
                    <a
                        href={`https://${brand.domain}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ color: '#007bff', textDecoration: 'none', fontSize: '1.1rem' }}
                    >
                        {brand.domain}
                    </a>
                </div>
                <button
                    onClick={() => {
                        if (!isEditing) {
                            setEditData({
                                instagramUrl: brand.instagramUrl || '',
                                tiktokUrl: brand.tiktokUrl || '',
                                tags: brand.tags ? brand.tags.join(', ') : '',
                                baseCurrency: brand.baseCurrency || 'USD'
                            });
                        }
                        setIsEditing(!isEditing);
                    }}
                    style={{
                        padding: '8px 16px',
                        backgroundColor: isEditing ? '#f0f0f0' : '#000',
                        color: isEditing ? '#333' : '#fff',
                        border: '1px solid #ccc',
                        borderRadius: '6px',
                        cursor: 'pointer',
                        fontWeight: 500
                    }}
                >
                    {isEditing ? 'Cancel' : 'Edit Info'}
                </button>
                <button
                    onClick={async () => {
                        if (!window.confirm(`Are you sure you want to delete "${brand.name}"? This will remove all collections, products, and social posts for this brand.`)) return;
                        try {
                            const res = await fetch(`/api/brands/${brandId}`, { method: 'DELETE' });
                            if (res.ok) {
                                navigate('/brands');
                            } else {
                                const data = await res.json();
                                alert(data.message || 'Delete failed');
                            }
                        } catch (err) {
                            console.error(err);
                            alert('Error deleting brand');
                        }
                    }}
                    style={{
                        padding: '8px 16px',
                        backgroundColor: '#c0392b',
                        color: '#fff',
                        border: 'none',
                        borderRadius: '6px',
                        cursor: 'pointer',
                        fontWeight: 500,
                        marginLeft: '8px'
                    }}
                >
                    Delete Brand
                </button>
            </header>

            {/* Scraping Indicator for New Brands */}
            {brand.createdAt && (new Date() - new Date(brand.createdAt)) < 1000 * 60 * 2 && (
                <div style={{
                    backgroundColor: '#fff3e0',
                    color: '#e65100',
                    padding: '16px',
                    borderRadius: '8px',
                    marginBottom: '24px',
                    border: '1px solid #ffcc80',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    boxShadow: '0 2px 8px rgba(230, 81, 0, 0.1)'
                }}>
                    <span style={{ fontSize: '1.4rem' }}>ATTENTION</span>
                    <div>
                        <strong style={{ display: 'block', fontSize: '1.05rem', marginBottom: '4px' }}>Scraping in progress...</strong>
                        <p style={{ margin: 0, fontSize: '0.95rem' }}>
                            We are actively pulling products, collections, and social posts for this brand right now.
                            <strong> Please wait ~60 seconds and refresh the page</strong>
                        </p>
                    </div>
                </div>
            )}

            {/* Metadata Section */}
            <section style={{
                backgroundColor: 'white',
                padding: '24px',
                borderRadius: '12px',
                border: '1px solid #eaeaea',
                marginBottom: '32px'
            }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <h3 style={{ marginTop: 0 }}>Details</h3>
                    {isEditing && (
                        <button
                            onClick={async () => {
                                try {
                                    const res = await fetch(`/api/brands/${brandId}`, {
                                        method: 'PUT',
                                        headers: { 'Content-Type': 'application/json' },
                                        body: JSON.stringify({
                                            instagramUrl: editData.instagramUrl,
                                            tiktokUrl: editData.tiktokUrl,
                                            tags: editData.tags.split(',').map(t => t.trim()).filter(Boolean),
                                            baseCurrency: editData.baseCurrency.toUpperCase().trim()
                                        })
                                    });
                                    if (res.ok) {
                                        const updatedBrand = await res.json();
                                        setBrand(updatedBrand);
                                        setIsEditing(false);
                                    } else {
                                        console.error('Failed to update brand');
                                    }
                                } catch (err) {
                                    console.error(err);
                                }
                            }}
                            style={{
                                padding: '6px 12px',
                                backgroundColor: '#b17c1bff',
                                color: '#fff',
                                border: 'none',
                                borderRadius: '6px',
                                cursor: 'pointer',
                                fontWeight: 500
                            }}
                        >
                            Save Changes
                        </button>
                    )}
                </div>
                {analyticsAllProducts && (
                    <div style={{ marginBottom: '16px' }}>
                        <p style={{ margin: '0 0 4px 0', fontSize: '1rem', fontWeight: 500 }}>
                            Average Price of all products: {analyticsAllProducts.currency && analyticsAllProducts.currency.toUpperCase() !== 'USD'
                                ? `${analyticsAllProducts.average_price} ${analyticsAllProducts.currency}`
                                : `$${analyticsAllProducts.average_price}`}
                        </p>
                        {analyticsAllProducts.currency && analyticsAllProducts.currency.toUpperCase() !== 'USD' && rates && (
                            <p style={{ margin: 0, color: '#888', fontSize: '0.9rem' }}>
                                ≈ ${convertToUSD(analyticsAllProducts.average_price, analyticsAllProducts.currency).toFixed(2)} USD
                            </p>
                        )}
                    </div>
                )}
                {!analyticsAllProducts && <p>Average Price of all products: Loading</p>}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '24px' }}>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Instagram</span>
                        {isEditing ? (
                            <input
                                type="text"
                                value={editData.instagramUrl}
                                onChange={(e) => setEditData({ ...editData, instagramUrl: e.target.value })}
                                style={{ width: '100%', padding: '6px', marginTop: '4px', borderRadius: '4px', border: '1px solid #ccc' }}
                            />
                        ) : brand.instagramUrl ? (
                            <a href={brand.instagramUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#333' }}>
                                {brand.instagramUrl}
                            </a>
                        ) : (
                            <span>-</span>
                        )}
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>TikTok</span>
                        {isEditing ? (
                            <input
                                type="text"
                                value={editData.tiktokUrl}
                                onChange={(e) => setEditData({ ...editData, tiktokUrl: e.target.value })}
                                style={{ width: '100%', padding: '6px', marginTop: '4px', borderRadius: '4px', border: '1px solid #ccc' }}
                            />
                        ) : brand.tiktokUrl ? (
                            <a href={brand.tiktokUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#333' }}>
                                {brand.tiktokUrl}
                            </a>
                        ) : (
                            <span>-</span>
                        )}
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Total Collections</span>
                        <span style={{ fontSize: '18px', fontWeight: 500 }}>{brand.collection_count}</span>
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Tags</span>
                        {isEditing ? (
                            <input
                                type="text"
                                value={editData.tags}
                                placeholder="Comma separated tags"
                                onChange={(e) => setEditData({ ...editData, tags: e.target.value })}
                                style={{ width: '100%', padding: '6px', marginTop: '4px', borderRadius: '4px', border: '1px solid #ccc' }}
                            />
                        ) : (
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '4px' }}>
                                {brand.tags && brand.tags.length > 0 ? brand.tags.map(tag => (
                                    <span key={tag} style={{ background: '#f0f0f0', padding: '2px 8px', borderRadius: '4px', fontSize: '12px' }}>
                                        #{tag}
                                    </span>
                                )) : <span>-</span>}
                            </div>
                        )}
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Base Currency</span>
                        {isEditing ? (
                            <input
                                type="text"
                                value={editData.baseCurrency}
                                placeholder="e.g. USD, EUR, NOK"
                                onChange={(e) => setEditData({ ...editData, baseCurrency: e.target.value })}
                                style={{ width: '100%', padding: '6px', marginTop: '4px', borderRadius: '4px', border: '1px solid #ccc' }}
                            />
                        ) : (
                            <div style={{ marginTop: '4px', fontSize: '16px', fontWeight: 500 }}>
                                {brand.baseCurrency || 'USD'}
                            </div>
                        )}
                    </div>
                </div>
                {analytics && (
                    <section style={{ marginTop: '32px', padding: '24px', background: 'white', borderRadius: '12px' }}>
                        <h3>Details on T-Shirts</h3>
                        <p style={{ margin: '0 0 4px 0' }}>
                            Average Price: {analytics.currency && analytics.currency.toUpperCase() !== 'USD' ? `${analytics.average_price} ${analytics.currency}` : `$${analytics.average_price}`}
                        </p>
                        {analytics.currency && analytics.currency.toUpperCase() !== 'USD' && rates && (
                            <p style={{ margin: '0 0 16px 0', color: '#888', fontSize: '0.9rem' }}>
                                ≈ ${convertToUSD(analytics.average_price, analytics.currency).toFixed(2)} USD
                            </p>
                        )}
                        <div style={{ height: 400 }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                                    <CartesianGrid />
                                    <XAxis type="category" dataKey="title" name="Product" hide />
                                    <YAxis type="number" dataKey="price" name="Price" unit={analytics.currency && analytics.currency.toUpperCase() !== 'USD' ? ` ${analytics.currency}` : '$'} />
                                    <Tooltip cursor={{ strokeDasharray: '3 3' }} defaultIndex={1} />
                                    <Scatter activeShape={{ fill: 'red' }} name="Products" data={analytics.products} fill="#8884d8" />
                                    <ReferenceLine y={analytics.average_price} stroke="grey" label="Avg Price" />
                                </ScatterChart>
                            </ResponsiveContainer>
                        </div>
                    </section>
                )}
                {analyticsHoodies && (
                    <section style={{ marginTop: '32px', padding: '24px', background: 'white', borderRadius: '12px' }}>
                        <h3>Details on Hoodies</h3>
                        <p style={{ margin: '0 0 4px 0' }}>
                            Average Price: {analyticsHoodies.currency && analyticsHoodies.currency.toUpperCase() !== 'USD' ? `${analyticsHoodies.average_price} ${analyticsHoodies.currency}` : `$${analyticsHoodies.average_price}`}
                        </p>
                        {analyticsHoodies.currency && analyticsHoodies.currency.toUpperCase() !== 'USD' && rates && (
                            <p style={{ margin: '0 0 16px 0', color: '#888', fontSize: '0.9rem' }}>
                                ≈ ${convertToUSD(analyticsHoodies.average_price, analyticsHoodies.currency).toFixed(2)} USD
                            </p>
                        )}
                        <div style={{ height: 400 }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                                    <CartesianGrid />
                                    <XAxis type="category" dataKey="title" name="Product" hide />
                                    <YAxis type="number" dataKey="price" name="Price" unit={analyticsHoodies.currency && analyticsHoodies.currency.toUpperCase() !== 'USD' ? ` ${analyticsHoodies.currency}` : '$'} />
                                    <Tooltip cursor={{ strokeDasharray: '3 3' }} defaultIndex={1} />
                                    <Scatter activeShape={{ fill: 'red' }} name="Products" data={analyticsHoodies.products} fill="#8884d8" />
                                    <ReferenceLine y={analyticsHoodies.average_price} stroke="grey" label="Avg Price" />
                                </ScatterChart>
                            </ResponsiveContainer>
                        </div>
                    </section>
                )}
                {distribution.length > 0 && (
                    <section style={{ marginTop: '32px', padding: '24px', background: 'white', borderRadius: '12px' }}>
                        <h3>Product Type Distributions for {brand.name}</h3>
                        <div style={{ height: 400 }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie
                                        data={distribution}
                                        cx="50%"
                                        cy="50%"
                                        labelLine={false}
                                        label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                                        outerRadius={150}
                                        fill="#8884d8"
                                        dataKey="value"
                                    >
                                        {distribution.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                        ))}
                                    </Pie>
                                    <Tooltip />
                                </PieChart>
                            </ResponsiveContainer>
                        </div>
                    </section>
                )}
            </section>

            <section>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                    <h2 style={{ margin: 0 }}>Collections Sneak Peek</h2>
                </div>

                {brand.collections && brand.collections.length > 0 ? (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '20px' }}>
                        {brand.collections.slice(0, 4).map(collection => (
                            <div key={collection._id} style={{
                                backgroundColor: 'white',
                                padding: '20px',
                                borderRadius: '12px',
                                border: '1px solid #eaeaea'
                            }}>
                                <h4 style={{ margin: '0 0 8px 0' }}>{collection.title}</h4>
                                <Link to={`/collections/${collection._id}`} style={{ fontSize: '0.9rem', color: '#007bff', textDecoration: 'none' }}>
                                    See details &rarr;
                                </Link>
                            </div>
                        ))}
                    </div>
                ) : (
                    <p style={{ color: '#666' }}>No collections found yet. Scraper might still be running.</p>
                )}
            </section>

            <section style={{ marginTop: '48px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                    <h2 style={{ margin: 0 }}>Social Activity</h2>
                </div>
                <BrandSocials brandId={brandId} />
            </section>
        </div >
    );
}
