/**
 * BrandDetails.jsx
 * 
 * This is the page for managing brand details.
 * It displays a list of brand details 
 * Some styling was generated by AI with expirmenation (Inline Vscode IDE Microsoft Copilot) on what looked the best visually (This file is still a work in progress)
 * Expiremantion on this file is still in progress
 * AI helped with debugging the brand fetching in the back end a lot (Inline Vscode IDE Microsoft Copilot) when I was stuck on why my brands werent showing up + displaying the collections. I was having issues with the collections not showing up. 
 * Specific debgubg and working code snippets (lines 21-32, 99-108, 118 -133)
 */
import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';

export default function BrandDetails() {
    const { brandId } = useParams();
    const [brand, setBrand] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchBrand = async () => {
            try {
                const res = await fetch(`/api/brands/details/${brandId}`);
                if (res.ok) {
                    const data = await res.json();
                    setBrand(data);
                }
            } catch (error) {
                console.error("Failed to fetch brand", error);
            } finally {
                setLoading(false);
            }
        };
        fetchBrand();
    }, [brandId]);

    if (loading) return <div style={{ padding: 24 }}>Loading...</div>;

    // Debugging View if not found
    if (!brand) {
        return (
            <div style={{ padding: 24 }}>
                <h2>Brand not found</h2>
                <p>Could not find brand with ID: <strong>{brandId}</strong></p>
                <p>Please return to the <Link to="/brands">Brands List</Link>.</p>
            </div>
        );
    }

    return (
        <div style={{ padding: '24px', paddingBottom: '100px' }}>
            {/* Breadcrumbs */}
            <nav style={{ marginBottom: '24px', fontSize: '14px', color: '#666' }}>
                <Link to="/" style={{ color: '#888', textDecoration: 'none' }}>Home</Link>
                <span style={{ margin: '0 8px' }}>&gt;</span>
                <Link to="/brands" style={{ color: '#888', textDecoration: 'none' }}>Brands</Link>
                <span style={{ margin: '0 8px' }}>&gt;</span>
                <span style={{ color: '#333', fontWeight: 500 }}>{brand.name}</span>
            </nav>

            {/* Header */}
            <header style={{ marginBottom: '32px' }}>
                <h1 style={{ margin: '0 0 8px 0', fontSize: '2.5rem' }}>{brand.name}</h1>
                <a
                    href={`https://${brand.domain}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ color: '#007bff', textDecoration: 'none', fontSize: '1.1rem' }}
                >
                    {brand.domain}
                </a>
            </header>

            {/* Metadata Section */}
            <section style={{
                backgroundColor: 'white',
                padding: '24px',
                borderRadius: '12px',
                border: '1px solid #eaeaea',
                marginBottom: '32px'
            }}>
                <h3 style={{ marginTop: 0 }}>Details</h3>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '24px' }}>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Instagram</span>
                        {brand.instagramUrl ? (
                            <a href={brand.instagramUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#333' }}>
                                {brand.instagramUrl}
                            </a>
                        ) : (
                            <span>-</span>
                        )}
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Total Collections</span>
                        <span style={{ fontSize: '18px', fontWeight: 500 }}>{brand.collection_count}</span>
                    </div>

                    <div>
                        <span style={{ display: 'block', fontSize: '12px', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Tags</span>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '4px' }}>
                            {brand.tags && brand.tags.length > 0 ? brand.tags.map(tag => (
                                <span key={tag} style={{ background: '#f0f0f0', padding: '2px 8px', borderRadius: '4px', fontSize: '12px' }}>
                                    #{tag}
                                </span>
                            )) : <span>-</span>}
                        </div>
                    </div>
                </div>
            </section>

            {/* Collections Sneak Peek */}
            <section>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                    <h2 style={{ margin: 0 }}>Collections Sneak Peek</h2>
                </div>

                {brand.collections && brand.collections.length > 0 ? (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '20px' }}>
                        {brand.collections.slice(0, 4).map(collection => (
                            <div key={collection._id} style={{
                                backgroundColor: 'white',
                                padding: '20px',
                                borderRadius: '12px',
                                border: '1px solid #eaeaea'
                            }}>
                                <h4 style={{ margin: '0 0 8px 0' }}>{collection.title}</h4>
                            </div>
                        ))}
                    </div>
                ) : (
                    <p style={{ color: '#666' }}>No collections found yet. Scraper might still be running.</p>
                )}
            </section>
        </div>
    );
}
